validation: sovereign
version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: charlie
  coins:
  - 5000token
  - 50000000stake
  mnemonic: play butter frown city voyage pupil rabbit wheat thrive mind skate turkey helmet thrive door either differ gate exhibit impose city swallow goat faint
faucet:
  name: alice
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
